exclude: '.zarr.'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--chars,"  "]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  -   repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
      - id: absolufy-imports
        name: absolufy-imports
  -   repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
      - id: isort
        language_version: python3
  -   repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
      - id: black
        language_version: python3
        args:
          - --target-version=py38
  -   repo: https://gitlab.com/pycqa/flake8.git
      rev: 3.8.0
      hooks:
      - id: flake8
        language_version: python3
