# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt --extra-index-url https://casa-pip.nrao.edu:443/repository/pypi-group/simple, https://casa-pip.nrao.edu/repository/pypi-casa-release/simple; fi

    - name: Test with pytest
      run: |
        pytest
